import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."); const out=path.join(root,"dist");
const ids=["critically-appraise-paper","interpret-effect-estimate","identify-confounding","assess-measurement-validity","choose-statistical-model"];
const skills=[]; for(const id of ids) skills.push(JSON.parse(await readFile(path.join(root,"skills",id,"skill.yaml"),"utf8")));
const stats=JSON.parse(await readFile(path.join(root,"domains/statistics/concepts/core-concepts.json"),"utf8")).core_concepts; const physics=JSON.parse(await readFile(path.join(root,"domains/physics/concepts/core-concepts.json"),"utf8")).core_concepts; const cross=[]; for(const f of ["measurement/concepts/validity.json","causal-inference/concepts/confounding.json"]) cross.push(JSON.parse(await readFile(path.join(root,"domains",f),"utf8")));
const known=new Set([...stats.map(c=>`statistics.${c.id}`),...physics.map(c=>`physics.${c.id}`),...cross.map(c=>c.id)]); const categories=["understand","appraise","design","analyze","synthesize"]; const maturities=["SKELETON","BASIC","EXECUTABLE","AUDITED"]; const graph={concept_to_skills:{},skill_to_concepts:{}}; const seen=new Set();
for(const s of skills){if(seen.has(s.id))throw new Error(`duplicate skill: ${s.id}`);seen.add(s.id);if(!s.categories?.every(c=>categories.includes(c)))throw new Error(`invalid taxonomy: ${s.id}`);if(!maturities.includes(s.maturity))throw new Error(`invalid maturity: ${s.id}`);if(s.maturity==="EXECUTABLE"&&["purpose","when_to_use","requires","inputs","steps","outputs","failure_modes","worked_example","limitations"].some(k=>!s[k]))throw new Error(`incomplete executable skill: ${s.id}`);const refs=s.requires.concepts;if(new Set(refs).size!==refs.length)throw new Error(`duplicate edge: ${s.id}`);const bad=refs.filter(x=>!known.has(x));if(bad.length)throw new Error(`unresolved concept: ${bad.join(",")}`);graph.skill_to_concepts[s.id]=refs;for(const c of refs)(graph.concept_to_skills[c]??=[]).push(s.id);}
const esc=s=>String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;"); const href=id=>id.startsWith("statistics.")?`/concepts/${id.slice(11)}/`:id.startsWith("physics.")?`/concepts/physics/${id.slice(8)}/`:`/concepts/${id}/`;
const html=s=>`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>${esc(s.title)} · Research OS</title></head><body><nav><a href="/">ホーム</a> · <a href="/skills/">Skills</a></nav><h1>${esc(s.title)}</h1><p>${esc(s.purpose)}</p><p>カテゴリ: ${s.categories.map(esc).join(", ")} ／ 成熟度: ${s.maturity}</p><h2>いつ使うか</h2><p>${esc(s.when_to_use)}</p><h2>必要なConcept</h2><ul>${s.requires.concepts.map(c=>`<li><a href="${href(c)}">${esc(c)}</a></li>`).join("")}</ul><h2>手順</h2><ol>${s.steps.map(x=>`<li>${esc(x.action)}</li>`).join("")}</ol><h2>失敗モード</h2><ul>${s.failure_modes.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><h2>Worked example</h2><p>${esc(s.worked_example)}</p><h2>限界</h2><ul>${s.limitations.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></body></html>`;
await mkdir(path.join(out,"generated"),{recursive:true}); await mkdir(path.join(out,"skills"),{recursive:true}); for(const s of skills){await mkdir(path.join(out,"skills",s.id),{recursive:true});await writeFile(path.join(out,"skills",s.id,"index.html"),html(s),"utf8");} await writeFile(path.join(out,"generated/concept-skill-graph.json"),JSON.stringify(graph,null,2),"utf8"); const all=[...known]; const coverage={total_concepts:all.length,total_skills:skills.length,skills_by_category:Object.fromEntries(categories.map(c=>[c,skills.filter(s=>s.categories.includes(c)).map(s=>s.id)])),skills_by_maturity:Object.fromEntries(maturities.map(m=>[m,skills.filter(s=>s.maturity===m).map(s=>s.id)])),concepts_used_by_at_least_one:Object.keys(graph.concept_to_skills).filter(c=>graph.concept_to_skills[c].length>=1),concepts_used_by_at_least_two:Object.keys(graph.concept_to_skills).filter(c=>graph.concept_to_skills[c].length>=2),orphan_concepts:all.filter(c=>!graph.concept_to_skills[c]),orphan_skills:skills.filter(s=>!s.requires.concepts.length).map(s=>s.id),edge_count:Object.values(graph.skill_to_concepts).reduce((n,x)=>n+x.length,0)}; await writeFile(path.join(out,"generated/skill-coverage.json"),JSON.stringify(coverage,null,2),"utf8"); console.log(`built ${skills.length} skills, ${coverage.edge_count} edges`);
